print("\n           Trust Fund Buddy\n\n")
print("Total your monthly spending so that your trust fund doesn't run out")
print("<and you're forced to get a real job>.\n\n")
print("please enter the requested, monthly costs.   Since you're rich, ignore pennies")
print("and use only dollar amounts.")
print("\n\n")
print("Lamborghini Tune-Ups:", end='')
var = int(input())
var = var + int(input("Manhattan Apartment: "))
var = var + int(input("Private Jet Rental: "))
var = var + int(input("Gifts: "))
var = var + int(input("Dinning Out: "))
var = var + int(input("Staff <butlers, chef, driver, assistant>: "))
var = var + int(input("Personal Guru and Coach: "))
var = var + int(input("Computer  Games: "))
print("\n Grand Total:   ",var)
print("\nPress the enter key to exit.")

