name = input("Hi.  What's your name? ")
age = int(input("And how old are you? "))
weigh = input("Okay, last question. How mnay pounds do you weigh? ")
print("\nDid you know that you're just 4 in dog years?\n")
print("But you're also over %d seconds old.\n"%(age * 60 * 60 * 24 * 365))
become = input("If a small child were trying to get your attention, your name would become: ")
print("\nDid you know that on the moon you would weigh only 27.5 pounds?")
print("But on the sun, you'd weigh 4471.5 <but, ah... not for long>.\n\n")
print("Press the enter key to exit.")
